### ISSUE TITLE
Take over docs from STM8 eForth issue 

### ISSUE THREAD

**Issue by TG9541** [TG9541/stm8ef-modbus#1]
The STM8 eForth issue https://github.com/TG9541/stm8ef/issues/238 contains quite some initial technical documentation that should be moved to Wiki pages in this repository.

**Comment by TG9541** [comment]
I added some [findings on the original firmware to the Wiki](https://github.com/TG9541/stm8ef-modbus/wiki/C0135-Original-Firmware-Properties).

Honestly, I can't make heads or tails of it and I'm giving up. 

Maybe @bademux, @tealbrains  or @anklimov have something to add...

**Comment by tealbrains** [comment]
@TG9541 I would not even waste time trying to reverse engineer that thing. Your solution is much better than the "stock" mumbo-jumbo. The stock modbus timing is out and I think that should say it all. When I realised that, I unplugged everything and went online to see if there was an alternative firmware. Any owner of this board should see it as a hardware-only product and will hopefully stumble upon your binary to make it work as a Modbus slave :)

**Comment by bademux** [comment]
@tealbrains it is worth to leave comment on Aliexpress with link to the project. (sorry for my 5c)

**Comment by TG9541** [comment]
@bademux seeding some links through the vendor feedback can work in some cases but there are potentially many vendors and the search index impact of comments there is probably low. Forums, sites like HaD are much better for spreading the word! Some "online module shops" also link to this repository (and many more to the STM8 eForth C0135 wiki page),

@tealbrains some of the fun I'm getting out of this project is doing the unlikely, namely making people look at a technology that at first glance only creates cognitive dissonance. I'm experimenting with ways to make people continue reading (e.g. by first creating cognitive ease), and that learning even helps me in my "daytime job".

IMHO Aussies have a significantly higher tolerance for new things. It could also be the case hat the source of most things odd is Down Under (-> Black Swan), but that's just a conjecture based on a relatively small sample ;-)
