### ISSUE TITLE
STM32F030F4 2-Relay Board

### ISSUE THREAD

**Issue by sebstud** [TG9541/stm8ef-modbus#39]
Hi,
great project! Will it be possible to implement eForth modbus RTU for very cheep relay board based on STM32F030F4 like this:
https://www.aliexpress.com/item/4000817530793.html?spm=a2g0o.cart.0.0.37833c00zITqOg&mp=1
With the stm8 I can find only the bigger version 4-relay, which is complicate to place in the small box. I don't no why there are only 4-relay with stm8 chip.   
Please help me to find out the solution.

**Comment by TG9541** [comment]
@sebstud the STM32F030F4 is certainly a µC with very good price/feature ratio but I have no plans to support anything else but the STM8 family in the near future.

What might work for you is assembling a node using standard boards: a blue STM8S103 board, a single or twin relay board and a RS485 transceiver.
